### ISSUE TITLE
[FEATURE REQUEST] - Updated desktop decryption script

### ISSUE THREAD

**Issue by xxxserxxx** [Arctosoft/Valv-Android#104]
With the old encryption mechanism and the script in #33, we had a way of decrypting files on desktops. The script no longer works since the recent changes; the link to the script was removed from [ENCRYPTION.md](/Arctosoft/Valv-Android/blob/master/ENCRYPTION.md).

It'd be nice to have an updated script that works with the new encryption mechanism.

**Comment by xxxserxxx** [comment]
Spent some time today and did it myself.

The project is called [dvalv](https://hg.sr.ht/~ser/dvalv). The repos is on Sourcehut. It's in Go and can be installed with `go install ser1.net/dvalv@latest`; CI is also building Linux (arm64 & amd64), Windows (amd64), and Darwin (amd64) binaries.

It is in its current state quite basic: it decrypts Valv v2-format files, using the embeded metadata to reconstitute the original file name. Very probably, I'll make it concurrent and recursive for processing entire directories, and support encrypting

**Comment by xxxserxxx** [comment]
dvalv now supports:

- encryption (v2 format)
- decryption of both v1 and v2 formats
- disable-able concurrent processing, for taking advantage of multiple cores
- pulling the password from a secret service (a-la [rook](https://hg.sr.ht/~ser/rook), libsecret, keepassxc, kwallet, etc)
- configurable verbosity
- recursive processing, if given directories; directory structure in destination is preserved
- multiple file arguments

**Comment by xxxserxxx** [comment]
dvalv is at 0.5.3; it had a lot of bugs between 0.5.0 and 0.5.3, including not actually recursing into subdirectories and a much worse failure to close (and, therefore, flush) the output on encryption, but it's probably at a point I'll stop fussing with it.

The one thing I may do is swap out the filetype detection library. I grabbed it nearly at random, and it's pretty limited in terms of suffix recognition, and it oddly has no support for most text file types. However, I'm not using the magic numbers feature, which would require either a lot of hoop-jumping or reading file contents twice, and maybe it'd be worth the effort.

However, my objective with dvalv was decryption; encryption was just a target of opportunity, and is not something I'm going to spend a lot of time on. For decryption, file type detection is not relevant.

**Comment by JakubIgnacyGorski** [comment]
Amazing job @xxxserxxx! I created a simple script to decrypt whole folders and back them up in another directory. It's much less complex than your solution, but it's enough for me.

Here is [my repo](https://github.com/JakubIgnacyGorski/valv-decryption) with the script.

**Comment by xxxserxxx** [comment]
@JakubIgnacyGorski Simple is good! I don't "do" Python, or else my solution probably would have been to just update the old  Python script.

What would be _really_ nice is a fuse library for mounting dvalv directories, like gocryptfs. That's what I _should_ have done. Really, my objective was to be able to clean stuff off my phone, but being able to keep it encrypted would be neat... Hmmm...
