### ISSUE TITLE
[BUG] - GIF files do not work anymore

### ISSUE THREAD

**Issue by robinpaul85** [Arctosoft/Valv-Android#105]
**Describe the bug**
With the latest update to the version on Fdroid, GIF files do not open anymore. It can still be opened using some other image viewing software by "caching" to it but it does not open inside the app anymore.
**To Reproduce**
Download the latest Fdroid build. Try opening a GIF stored inside the valv.

**Expected behavior**

**Additional context**

**Comment by hej2010** [comment]
Can you share a GIF that is not working?
I tried with several and they work and play fine for me

**Comment by robinpaul85** [comment]
ok, I see what the problem is. GIFs encrypted by the previous version of valv cannot be displayed anymore. When I exported the GIF and then imported it again (using the latest version). It worked. But, its kind of a tedious having to do with all the photos in an album. Is there a fix for it which will make the latest version back compatible with earlier versions?

**Comment by hej2010** [comment]
Strange, I will try to fix it
