### ISSUE TITLE
[BUG] - F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Arctosoft/Valv-Android#107]
**Describe the bug**
In https://github.com/Arctosoft/Valv-Android/commit/1b848dd10d03c1a42e916647a37e7dc60729d60a some libs are updated to 2.8.5 but in the aboutlibraries file in your apk they are still 2.8.4. Could you please rebuild the apk? Thanks!

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by hej2010** [comment]
A new apk has been uploaded for that release :)

**Comment by linsui** [comment]
Thanks!
