### ISSUE TITLE
[FEATURE REQUEST] - All Images View

### ISSUE THREAD

**Issue by plutonium-239** [Arctosoft/Valv-Android#15]
I find that the only thing lacking in this app is a global image view, like the inbuilt gallery app does.

It would be great to have an "all images" view (probably sorted by date).

Are there any chances of implementing that?

**Comment by hej2010** [comment]
Good idea, it has been added in [v1.4.0](https://github.com/Arctosoft/Valv-Android/releases/tag/v1.4.0) :)
