### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [Arctosoft/Valv-Android#18]
May I ask what license you've chosen for your app? Some of the files in this repo state Apache-2.0, but nothing is declared on the repo. Thanks in advance for clarification!

**Comment by IzzySoft** [comment]
Cool, thanks! With that, your app will become [available here](https://apt.izzysoft.de/packages/se.arctosoft.vault/) at around 6 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :star_struck: And if you want to get your app into the "primary" repo of F-Droid.org itself (according to the results of my scanners, it should meet the inclusion criteria there) let me know and I can probably help you with that, too (disclosure: I'm one of the maintainers there).

**Comment by hej2010** [comment]
Ok, nice! I created a merge request on F-Droid

**Comment by IzzySoft** [comment]
Wow! You're not doing things by halves, do you? Congrats! See you over there then, probably…
