### ISSUE TITLE
[FEATURE REQUEST] - Hide encrypted files

### ISSUE THREAD

**Issue by KolyaKorruptis** [Arctosoft/Valv-Android#24]
Having a bunch of clearly encrypted files (with the name of the encryption app in their titles(!) and their original file extensions) lying around will cause suspicion in even the most amateur snooping around. Please consider hiding encrypted files and/or folders.

**Comment by ricassiocosta** [comment]
You can create folders starting with a dot (.my_folder) to hide this folder by default in the filesystem. Definitely not the fancy solution, but it works for the "most amateur snooping".
