### ISSUE TITLE
[BUG] - F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [Arctosoft/Valv-Android#43]
**Describe the bug**
In the json generated by aboutLibraries there is a block for androidx.media3:media3-exoplayer-hls but there is no such block in the F-Droid build.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy]
 - OS: [e.g. Android 12]
 - Version [e.g. 1.0]

**Additional context**

**Comment by hej2010** [comment]
Should I create a new release or is it enough to update the .apk in the two most recent releases?

**Comment by hej2010** [comment]
I recompiled and uploaded the fixed .apk for release 1.6.0 and 1.6.1

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
@hej2010 just a heads up, pls build APKs from the Tagged commit in the future,else this happens: https://gitlab.com/fdroid/fdroiddata/-/jobs/6515204066#L1664

fixed in: https://gitlab.com/fdroid/fdroiddata/-/commit/9f72a304b23c9435172b04c4c24c62ea9bbf7b4b

**Comment by hej2010** [comment]
> @hej2010 just a heads up, pls build APKs from the Tagged commit in the future,else this happens: https://gitlab.com/fdroid/fdroiddata/-/jobs/6515204066#L1664
> 
> fixed in: https://gitlab.com/fdroid/fdroiddata/-/commit/9f72a304b23c9435172b04c4c24c62ea9bbf7b4b

Ah, ok, I thought it was by version name/code only. Will do that in future updates :)

**Comment by licaon-kter** [comment]
Well, not sure why the APK has the "commithash" inside, but it is what it is. We see this in other apps too.

**Comment by licaon-kter** [comment]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7908196810#L370

difflog: [valv30.log](https://github.com/user-attachments/files/17130922/valv30.log)

@hej2010 maybe you can clean the caches and rebuild? attach the apk here so we can test

**Comment by hej2010** [comment]
@licaon-kter Sure, here 
[Vault_30_1.11.0_release.zip](https://github.com/user-attachments/files/17131006/Vault_30_1.11.0_release.zip) (could not upload .apk)

**Comment by licaon-kter** [comment]
I see that you've updated the APK in release :) and that one is repro :tada: https://gitlab.com/fdroid/fdroiddata/-/commit/c32a74ae05d1b45fecae7dd6637f6a453ae530d2
